INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552574 is handled. Duration 1172 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552573 is handled. Duration 1202 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552575 is handled. Duration 516 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552577 is handled. Duration 1125 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552576 is handled. Duration 2437 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552578 is handled. Duration 530 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552579 is handled. Duration 390 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552580 is handled. Duration 1515 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552587 is handled. Duration 920 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552588 is handled. Duration 718 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552589 is handled. Duration 422 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Polling stopped
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552590 is handled. Duration 452 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552591 is handled. Duration 469 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552593 is handled. Duration 375 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552592 is handled. Duration 22000 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552594 is handled. Duration 313 ms by bot id=8021425710
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552598 is not handled. Duration 0 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552600 is not handled. Duration 0 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552595 is handled. Duration 453 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552596 is handled. Duration 515 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552599 is handled. Duration 515 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552601 is handled. Duration 155 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552602 is handled. Duration 764 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552603 is handled. Duration 93 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552604 is handled. Duration 438 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552605 is not handled. Duration 15 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552606 is not handled. Duration 0 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552607 is handled. Duration 514 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552608 is handled. Duration 327 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552609 is handled. Duration 328 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552610 is handled. Duration 155 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552611 is handled. Duration 187 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552612 is handled. Duration 312 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552613 is handled. Duration 344 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552614 is handled. Duration 219 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552615 is handled. Duration 422 ms by bot id=8021425710
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 64] ��������� ������� ��� ����� ����������
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 8021425710)
INFO:aiogram.event:Update id=884552616 is handled. Duration 421 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552617 is handled. Duration 109 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552618 is handled. Duration 266 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552619 is handled. Duration 500 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552620 is handled. Duration 514 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552621 is handled. Duration 311 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552622 is not handled. Duration 0 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552622 by bot id=8021425710
ValidationError: 2 validation errors for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
poster
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 100, in film_poster
    film = Film(**data)
           ^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
poster
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
INFO:aiogram.event:Update id=884552623 is handled. Duration 313 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552624 is handled. Duration 187 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552625 is handled. Duration 171 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552626 is handled. Duration 264 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552627 is handled. Duration 328 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552628 is handled. Duration 234 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552629 is not handled. Duration 0 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552629 by bot id=8021425710
ValidationError: 1 validation error for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 100, in film_poster
    film = Film(**data)
           ^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
INFO:aiogram.event:Update id=884552630 is not handled. Duration 0 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552630 by bot id=8021425710
ValidationError: 1 validation error for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 100, in film_poster
    film = Film(**data)
           ^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
INFO:aiogram.event:Update id=884552631 is handled. Duration 250 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552632 is handled. Duration 186 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552633 is handled. Duration 108 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552634 is handled. Duration 108 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552635 is handled. Duration 125 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552636 is handled. Duration 171 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552637 is not handled. Duration 0 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552637 by bot id=8021425710
ValidationError: 1 validation error for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 100, in film_poster
    film = Film(**data)
           ^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\pydantic\main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for Film
rating
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='10/10', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/float_parsing
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.290757 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.511593 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.979755 seconds and try again... (tryings = 3, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.473840 seconds and try again... (tryings = 4, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 5, bot id = 8021425710)
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552653 is handled. Duration 311 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552654 is handled. Duration 389 ms by bot id=8021425710
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552655 is handled. Duration 250 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552656 is handled. Duration 593 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552657 is handled. Duration 171 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552658 is handled. Duration 218 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552659 is handled. Duration 296 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552660 is handled. Duration 390 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552661 is handled. Duration 188 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552662 is handled. Duration 735 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552663 is handled. Duration 125 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552664 is handled. Duration 171 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552665 is handled. Duration 234 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552666 is handled. Duration 110 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552667 is handled. Duration 313 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552668 is handled. Duration 125 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552669 is handled. Duration 250 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552670 is handled. Duration 188 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552671 is not handled. Duration 1250 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552671 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552672 is not handled. Duration 733 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552672 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552673 is handled. Duration 186 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552674 is not handled. Duration 468 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552674 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552675 is not handled. Duration 671 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552675 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552676 is handled. Duration 796 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552677 is handled. Duration 250 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552678 is handled. Duration 218 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552679 is handled. Duration 203 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552680 is handled. Duration 93 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552681 is handled. Duration 93 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552682 is handled. Duration 281 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552683 is handled. Duration 281 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552684 is handled. Duration 281 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552685 is not handled. Duration 453 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552685 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552686 is not handled. Duration 719 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552686 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552687 is not handled. Duration 1937 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552687 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552688 is handled. Duration 516 ms by bot id=8021425710
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552689 is handled. Duration 500 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552690 is handled. Duration 4468 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552691 is handled. Duration 2343 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552692 is handled. Duration 5031 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 8021425710)
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552693 is handled. Duration 281 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552694 is handled. Duration 250 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552695 is handled. Duration 264 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552696 is handled. Duration 625 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552697 is handled. Duration 437 ms by bot id=8021425710
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 8021425710)
INFO:aiogram.event:Update id=884552698 is handled. Duration 843 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552699 is handled. Duration 578 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552700 is handled. Duration 485 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552701 is not handled. Duration 641 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552701 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552702 is handled. Duration 1078 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552703 is handled. Duration 109 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552704 is handled. Duration 94 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552705 is handled. Duration 234 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552706 is handled. Duration 328 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552707 is handled. Duration 406 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552708 is handled. Duration 186 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552709 is handled. Duration 108 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552710 is handled. Duration 1139 ms by bot id=8021425710
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 64] ��������� ������� ��� ����� ����������
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.422521 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.672878 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.159949 seconds and try again... (tryings = 3, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.831736 seconds and try again... (tryings = 4, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 3.806881 seconds and try again... (tryings = 5, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 6, bot id = 8021425710)
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552712 is handled. Duration 562 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552713 is handled. Duration 93 ms by bot id=8021425710
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552714 is handled. Duration 280 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552715 is handled. Duration 280 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552716 is handled. Duration 218 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552717 is handled. Duration 297 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552718 is handled. Duration 108 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552719 is handled. Duration 156 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552720 is handled. Duration 532 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552721 is not handled. Duration 436 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552721 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.event:Update id=884552722 is handled. Duration 3625 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552723 is not handled. Duration 1312 ms by bot id=8021425710
ERROR:aiogram.event:Cause exception while process update id=884552723 by bot id=8021425710
TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
Traceback (most recent call last):
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 146, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 141, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\router.py", line 166, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "c:\Users\SergiiSkholarii\Desktop\python_lesson_bot\main.py", line 119, in calb_film
    await callback.message.answer_photo(
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
           ^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\bot.py", line 487, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\aiohttp.py", line 189, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SergiiSkholarii\Desktop\python_lesson_bot\.venv\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: IMAGE_PROCESS_FAILED
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552724 is handled. Duration 391 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552725 is handled. Duration 531 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552726 is handled. Duration 296 ms by bot id=8021425710
INFO:aiogram.event:Update id=884552727 is handled. Duration 2593 ms by bot id=8021425710
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.295184 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.727823 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.146968 seconds and try again... (tryings = 3, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 4, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.315528 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.504399 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.939763 seconds and try again... (tryings = 3, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 4, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [������� ����� ����������. �� ����������� � ���������� ������� � ���� ���������� � ���������� ������� Windows]
WARNING:aiogram.dispatcher:Sleep for 1.507239 seconds and try again... (tryings = 1, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.247509 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.523452 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.908343 seconds and try again... (tryings = 3, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.477044 seconds and try again... (tryings = 4, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 5, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [WinError 64] ��������� ������� ��� ����� ����������
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.315811 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.826802 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.561817 seconds and try again... (tryings = 3, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 3.246208 seconds and try again... (tryings = 4, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.330079 seconds and try again... (tryings = 5, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.018759 seconds and try again... (tryings = 6, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.839383 seconds and try again... (tryings = 7, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.995747 seconds and try again... (tryings = 8, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.999852 seconds and try again... (tryings = 9, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.053901 seconds and try again... (tryings = 10, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.791118 seconds and try again... (tryings = 11, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.928773 seconds and try again... (tryings = 12, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.944054 seconds and try again... (tryings = 13, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.034648 seconds and try again... (tryings = 14, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.929348 seconds and try again... (tryings = 15, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.875548 seconds and try again... (tryings = 16, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 17, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.442322 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.875855 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.496817 seconds and try again... (tryings = 3, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 3.223293 seconds and try again... (tryings = 4, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.315339 seconds and try again... (tryings = 5, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 5.130756 seconds and try again... (tryings = 6, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.918958 seconds and try again... (tryings = 7, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.928175 seconds and try again... (tryings = 8, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 4.933469 seconds and try again... (tryings = 9, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 10, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.342820 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.647629 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.955925 seconds and try again... (tryings = 3, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 2.498193 seconds and try again... (tryings = 4, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 3.246570 seconds and try again... (tryings = 5, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 6, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
WARNING:aiogram.dispatcher:Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.412742 seconds and try again... (tryings = 1, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 1.813359 seconds and try again... (tryings = 2, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.296812 seconds and try again... (tryings = 3, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 2.971578 seconds and try again... (tryings = 4, bot id = 8021425710)
ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorDNSError: Cannot connect to host api.telegram.org:443 ssl:default [getaddrinfo failed]
WARNING:aiogram.dispatcher:Sleep for 3.768220 seconds and try again... (tryings = 5, bot id = 8021425710)
INFO:aiogram.dispatcher:Connection established (tryings = 6, bot id = 8021425710)
INFO:aiogram.dispatcher:Polling stopped
INFO:aiogram.dispatcher:Polling stopped for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:__main__:Started
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @Film_liiamy_bot id=8021425710 - 'FilmBot'
INFO:aiogram.event:Update id=884552728 is handled. Duration 233 ms by bot id=8021425710
